- name: Playbook to run openstack roles through jumphost
  hosts: all
  gather_facts: yes
  sudo: yes
  roles:
    - osp-network
    - osp-keypair
    - osp-securitygroup
    - osp-facts
  tasks:
  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: frontend.yaml
  - name: Create app1 instance
    include_role:
       name: osp-instances
       vars_from: app1.yaml
  - name: Create app2 instance
    include_role:
       name: osp-instances
       vars_from: app2.yaml
  - name: Create db instance
    include_role:
       name: osp-instances
       vars_from: db.yaml 
